### PR TITLE
*: Various updates and stability changes

### PR DESCRIPTION
**Pull request by brancz**
Various changes that I had to do for testing the CPU performance regressions in 2.1.

@fabxc @Gouthamve @krasi-georgiev

### CODE REVIEW

**Comment by krasi-georgiev** [comment]
shouldn't  we wait and see what is the reply on https://github.com/crosscloudci/crosscloudci/issues/11 before we spend any more efforts here?

**Comment by brancz** [comment]
I had these changes laying around, so for the time being I figured it's better to share in case anyone wants/needs to spin up a cluster *now*.

**Comment by krasi-georgiev** [comment]
I guess if Fabian doesn't have any objections and you have access,I would say merge at will so it doesn't get lost in the pile and depending on the development with the CNCF CI can revisit this later if needed.

**Comment by fabxc** [comment]
👍

**Pull request merged**
